DM-45279: make donutPlotIntra, donutPlotExtra
lsst-ts/donut_viz pull request #2
Opened 2024-07-17 22:41 UTC by suberlak

2024-07-23 21:44 UTC, jmeyers314 requested changes
Thanks Chris!  Looks good to me.  Just one request about how things get uploaded to RubinTV.

2024-07-23 21:44 UTC, jmeyers314 commented on python/lsst/donut/viz/plotAOSTask.py
> +            if self.config.doRubinTVUpload:
I think instead of adding "_{defocal_position}" to the filename, can we use the intrafocal visitId for the intra donut and extrafocal visitId for the extra donut?  That way we can use the same column on RubinTV for both.

2024-08-01 19:21 UTC, suberlak commented on python/lsst/donut/viz/plotAOSTask.py
> +            if self.config.doRubinTVUpload:
Ok, I've added these changes below.

2024-08-05 18:59 UTC, jmeyers314 requested changes
I still have some questions...

2024-08-05 18:59 UTC, jmeyers314 commented on python/lsst/donut/viz/plotAOSTask.py
> +            ):
I think you need to dedent this line, please.

2024-08-05 18:59 UTC, jmeyers314 commented on python/lsst/donut/viz/plotAOSTask.py
> +            if self.config.doRubinTVUpload:
I think you need to keep `plotName="fp_donut_gallery"` in order for RubinTV to put it in the existing column (which I think should be the goal).

2024-08-05 18:59 UTC, jmeyers314 commented on python/lsst/donut/viz/plotAOSTask.py
> +                # seq_num is sometimes different for intra vs extra-focal if pistoning
Right, but aren't `inputRefs.donutStampsIntraVisit.dataId["visit"]` and `inputRefs.donutStampsExtraVisit.dataId["visit"]` the same here?  I.e., both the intra and extra focal donuts are written to the butler under the same (extra) dataId?  Maybe the intra-focal visit is saved in the metadata somewhere?  (If not, then we should add that!)

2024-08-06 19:39 UTC, suberlak commented on python/lsst/donut/viz/plotAOSTask.py
> +                # seq_num is sometimes different for intra vs extra-focal if pistoning
Ok, that's true - when I try running it I get `collection/20240806T192018Z/donutPlotExtra/20250820/g/g_01/5025082000942/donutPlotExtra_LSSTComCam_g_g_01_5025082000942_donutViz_940-942_direct_test_20240806T192018Z.png `and `collection/20240806T192018Z/donutPlotIntra/20250820/g/g_01/5025082000942/donutPlotIntra_LSSTComCam_g_g_01_5025082000942_donutViz_940-942_direct_test_20240806T192018Z.png` , i.e. the same `visit` for both `donutPlotExtra` and `donutPlotIntra`.  I don't see the `intra-focal`  visit stored anywhere in the metadata of `donutStamp` - it does store `defocal_position` , which is either `intra` or `extra` .  So `donutStamps[0].defocal_type` would have different value whether it's an extra-focal or intra-focal set of stamps. What do you think?

2024-08-06 19:50 UTC, jmeyers314 commented on python/lsst/donut/viz/plotAOSTask.py
> +                # seq_num is sometimes different for intra vs extra-focal if pistoning
I think that means we should probably add the visit (or maybe it should be exposure) id to the DonutStamps metadata.  Probably somewhere near [here](https://github.com/lsst-ts/ts_wep/blob/develop/python/lsst/ts/wep/task/cutOutDonutsBase.py#L463C1-L464C1).

2024-08-07 01:28 UTC, suberlak commented on python/lsst/donut/viz/plotAOSTask.py
> +            if self.config.doRubinTVUpload:
Ok, changed the name, and visit is now inherited from donut metadata.

2024-08-15 20:55 UTC, suberlak commented on python/lsst/donut/viz/aggregateVisit.py
> -        intraStamps = DonutStamps([])
Yes - instantiating it empty makes it not possible to add metadata later. Like in `cutOutDonutsBase` here https://github.com/lsst-ts/ts_wep/blob/9181ff611b6d3e79bfbc71cfd92fd76e309eeca7/python/lsst/ts/wep/task/cutOutDonutsBase.py#L491 So this is to allow to pass along the metadata.

2024-08-19 20:52 UTC, merged